language: c

# compilers to add to build matrix
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsdl2-dev libsdl2-ttf-dev

# scripts to run before build
before_script:
  - mkdir build
  - cd build
  - cmake ..

 # build app, and run tests (ie make & make test)
script:
  - cmake --build .
